#logging:
#  level:
#    org:
#      apache:
#        coyote:
#          http11: debug

#messages 위치 설정(기본은 messages임)
spring:
  messages:
    basename: messages, errors

#Http Session생성 후 응답에 쿠키 넣을 때 url에 tracking-mode 없애는 방법
server:
  servlet:
    session:
      tracking-modes: cookie